//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerTelescope.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServerTelescope.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du port du serveur de communication [7000:27015].
        /// </summary>
        public static string ConfigPortNumber {
            get {
                return ResourceManager.GetString("ConfigPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du port.
        /// </summary>
        public static string ConfigPortSerie {
            get {
                return ResourceManager.GetString("ConfigPortSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder les paramètres.
        /// </summary>
        public static string ConfigSave {
            get {
                return ResourceManager.GetString("ConfigSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serveur de communication avec Stellarium :.
        /// </summary>
        public static string ConfigTitle {
            get {
                return ResourceManager.GetString("ConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port série du télescope :.
        /// </summary>
        public static string ConfigTitle2 {
            get {
                return ResourceManager.GetString("ConfigTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position du téléscope.
        /// </summary>
        public static string CoordsCurrent {
            get {
                return ResourceManager.GetString("CoordsCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déclinaison.
        /// </summary>
        public static string CoordsDEC {
            get {
                return ResourceManager.GetString("CoordsDEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déstination.
        /// </summary>
        public static string CoordsGoto {
            get {
                return ResourceManager.GetString("CoordsGoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct ascentionnel.
        /// </summary>
        public static string CoordsRA {
            get {
                return ResourceManager.GetString("CoordsRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client connecté.
        /// </summary>
        public static string InitPlugInClientConnected {
            get {
                return ResourceManager.GetString("InitPlugInClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string InitPlugInInit {
            get {
                return ResourceManager.GetString("InitPlugInInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liaison vers :.
        /// </summary>
        public static string InitPlugInServerService {
            get {
                return ResourceManager.GetString("InitPlugInServerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objet stellarium=telescope.
        /// </summary>
        public static string InitPlugInServerSet {
            get {
                return ResourceManager.GetString("InitPlugInServerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorsque l&apos;objet pointé dans stellarium est le même
        ///que l&apos;objet pointé par le telescope cliquer ici..
        /// </summary>
        public static string InitPlugInServerSetInit {
            get {
                return ResourceManager.GetString("InitPlugInServerSetInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer.
        /// </summary>
        public static string InitPlugInServerStart {
            get {
                return ResourceManager.GetString("InitPlugInServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string InitPlugInServerStatus {
            get {
                return ResourceManager.GetString("InitPlugInServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellarium.
        /// </summary>
        public static string InitPlugInServerStellarium {
            get {
                return ResourceManager.GetString("InitPlugInServerStellarium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter.
        /// </summary>
        public static string InitPlugInServerStop {
            get {
                return ResourceManager.GetString("InitPlugInServerStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléscope.
        /// </summary>
        public static string InitPlugInServerTelescope {
            get {
                return ResourceManager.GetString("InitPlugInServerTelescope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion :.
        /// </summary>
        public static string InitPlugInServerTitle {
            get {
                return ResourceManager.GetString("InitPlugInServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réception.
        /// </summary>
        public static string Listener {
            get {
                return ResourceManager.GetString("Listener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivez la procédure :
        /// 1) pointez votre telescope sur une étoile connue 
        /// 2) sélectionnez cette étoile dans stellarium, 
        /// 3) pointer le télescope sur cette étoile dans stellarium CTR+0 pour afficher la fenêtre.
        /// 4) cliquer sur le bouton &apos;initialisation&apos;..
        /// </summary>
        public static string PlugInServerHelpInit {
            get {
                return ResourceManager.GetString("PlugInServerHelpInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer le serveur de communication  avec Stellarium.
        /// </summary>
        public static string PlugInServerStart {
            get {
                return ResourceManager.GetString("PlugInServerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rafraichir.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner le port série :.
        /// </summary>
        public static string SelectSerialPort {
            get {
                return ResourceManager.GetString("SelectSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test de la communication :.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
